// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT5L22SwQMdeU8FqW9dN521b-UmDzo6M8',
    appId: '1:277748633004:web:93f04af146b83d828d3e09',
    messagingSenderId: '277748633004',
    projectId: 'quad-count',
    authDomain: 'quad-count.firebaseapp.com',
    storageBucket: 'quad-count.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACm_mPjCj6WUUIqMHdPXCa-BAMIOMctj8',
    appId: '1:277748633004:android:ccc83c2857b93b438d3e09',
    messagingSenderId: '277748633004',
    projectId: 'quad-count',
    storageBucket: 'quad-count.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYKCeUca9IKAOYpegw7dHFOCmvrmWZYn0',
    appId: '1:277748633004:ios:168c60dc67637cd28d3e09',
    messagingSenderId: '277748633004',
    projectId: 'quad-count',
    storageBucket: 'quad-count.firebasestorage.app',
    iosBundleId: 'com.example.quadCount',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYKCeUca9IKAOYpegw7dHFOCmvrmWZYn0',
    appId: '1:277748633004:ios:168c60dc67637cd28d3e09',
    messagingSenderId: '277748633004',
    projectId: 'quad-count',
    storageBucket: 'quad-count.firebasestorage.app',
    iosBundleId: 'com.example.quadCount',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAT5L22SwQMdeU8FqW9dN521b-UmDzo6M8',
    appId: '1:277748633004:web:a835955590df9c578d3e09',
    messagingSenderId: '277748633004',
    projectId: 'quad-count',
    authDomain: 'quad-count.firebaseapp.com',
    storageBucket: 'quad-count.firebasestorage.app',
  );

}